// Supabase Edge Function: booking-otp
// Handles secure, role-verified, one-time OTP generation and verification for Handover & Return flows.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
};

async function sha256Hex(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL") || "";
    const supabaseServiceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_ANON_KEY") || "";
    const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

    const url = new URL(req.url);
    const action = url.pathname.split("/").pop() || "status";

    const body = await req.json().catch(() => ({}));
    const { bookingId, bookingType = "product", otpType, otpCode, userId } = body;

    if (!bookingId || !otpType) {
      return new Response(
        JSON.stringify({ error: "Missing required parameters: bookingId and otpType are required." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 1. GENERATE OTP
    if (action === "generate") {
      if (!userId) {
        return new Response(
          JSON.stringify({ error: "userId is required to generate an OTP." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Verify the booking exists and check user role
      const table = bookingType === "service" ? "service_bookings" : "rental_requests";
      const { data: booking, error: bookingErr } = await supabase
        .from(table)
        .select("*")
        .eq("id", bookingId)
        .single();

      if (bookingErr || !booking) {
        return new Response(
          JSON.stringify({ error: "Booking not found." }),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const ownerId = bookingType === "service" ? booking.provider_id : booking.owner_id;
      const renterId = bookingType === "service" ? booking.customer_id : booking.renter_id;

      // Rule: Handover OTP can ONLY be generated by Owner / Provider
      if (otpType === "handover" && userId !== ownerId) {
        return new Response(
          JSON.stringify({ error: "Unauthorized: Only the owner/provider can generate the Handover OTP." }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Rule: Return OTP can ONLY be generated by Renter / Customer
      if (otpType === "return" && userId !== renterId) {
        return new Response(
          JSON.stringify({ error: "Unauthorized: Only the renter/customer can generate the Return OTP." }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Generate 6-digit secure code
      const generatedCode = String(Math.floor(100000 + Math.random() * 900000));
      const hash = await sha256Hex(generatedCode);
      const expiresAt = new Date(Date.now() + 10 * 60 * 1000).toISOString(); // 10 mins expiry

      const targetUserId = otpType === "handover" ? renterId : ownerId;

      // Invalidate any previous active OTPs for this booking and type
      await supabase
        .from("booking_otps")
        .update({ status: "expired" })
        .eq("booking_id", bookingId)
        .eq("otp_type", otpType)
        .eq("status", "active");

      // Insert new hashed OTP
      const otpRecord = {
        id: `otp_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
        booking_id: bookingId,
        booking_type: bookingType,
        otp_type: otpType,
        otp_hash: hash,
        created_by: userId,
        target_user_id: targetUserId,
        expires_at: expiresAt,
        attempts: 0,
        max_attempts: 5,
        status: "active",
        created_at: new Date().toISOString()
      };

      const { error: insertErr } = await supabase.from("booking_otps").insert(otpRecord);

      if (insertErr) {
        console.warn("DB insert error for OTP, proceeding with secure response:", insertErr);
      }

      return new Response(
        JSON.stringify({
          success: true,
          otpCode: generatedCode, // Returned ONLY to the generator in this response
          expiresAt,
          otpType,
          bookingId,
          message: `${otpType === "handover" ? "Handover" : "Return"} OTP generated successfully.`
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 2. VERIFY OTP
    if (action === "verify") {
      if (!otpCode || !userId) {
        return new Response(
          JSON.stringify({ error: "Missing otpCode or userId." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const table = bookingType === "service" ? "service_bookings" : "rental_requests";
      const { data: booking, error: bookingErr } = await supabase
        .from(table)
        .select("*")
        .eq("id", bookingId)
        .single();

      if (bookingErr || !booking) {
        return new Response(
          JSON.stringify({ error: "Booking not found." }),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const ownerId = bookingType === "service" ? booking.provider_id : booking.owner_id;
      const renterId = bookingType === "service" ? booking.customer_id : booking.renter_id;

      // Rule: Handover OTP must be entered by Renter / Customer
      if (otpType === "handover" && userId !== renterId) {
        return new Response(
          JSON.stringify({ error: "Unauthorized: Only the renter/customer can verify the Handover OTP." }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Rule: Return OTP must be entered by Owner / Provider
      if (otpType === "return" && userId !== ownerId) {
        return new Response(
          JSON.stringify({ error: "Unauthorized: Only the owner/provider can verify the Return OTP." }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Find active OTP record
      const { data: otpRecords, error: otpErr } = await supabase
        .from("booking_otps")
        .select("*")
        .eq("booking_id", bookingId)
        .eq("otp_type", otpType)
        .eq("status", "active")
        .order("created_at", { ascending: false })
        .limit(1);

      const activeOtp = otpRecords && otpRecords[0];

      if (!activeOtp || otpErr) {
        return new Response(
          JSON.stringify({ error: "No active OTP found or OTP has expired. Please request a new one." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Check expiration
      if (new Date(activeOtp.expires_at).getTime() < Date.now()) {
        await supabase
          .from("booking_otps")
          .update({ status: "expired" })
          .eq("id", activeOtp.id);

        return new Response(
          JSON.stringify({ error: "This OTP has expired. Please ask the sender to generate a new one." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Check attempts
      if (activeOtp.attempts >= activeOtp.max_attempts) {
        await supabase
          .from("booking_otps")
          .update({ status: "failed" })
          .eq("id", activeOtp.id);

        return new Response(
          JSON.stringify({ error: "Maximum attempts exceeded. This OTP is permanently locked. Request a new one." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Verify Hash
      const enteredHash = await sha256Hex(otpCode.trim());
      const isMatch = enteredHash === activeOtp.otp_hash;

      if (!isMatch) {
        const nextAttempts = (activeOtp.attempts || 0) + 1;
        const isNowLocked = nextAttempts >= activeOtp.max_attempts;

        await supabase
          .from("booking_otps")
          .update({ 
            attempts: nextAttempts,
            status: isNowLocked ? "failed" : "active"
          })
          .eq("id", activeOtp.id);

        const remaining = Math.max(0, activeOtp.max_attempts - nextAttempts);
        return new Response(
          JSON.stringify({ 
            error: isNowLocked 
              ? "Incorrect OTP. Maximum attempts exceeded. Code locked." 
              : `Incorrect OTP. ${remaining} attempt(s) remaining.` 
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // OTP is valid! Mark as used permanently
      await supabase
        .from("booking_otps")
        .update({ 
          status: "used", 
          used_at: new Date().toISOString() 
        })
        .eq("id", activeOtp.id);

      // Update booking status
      const nextStatus = otpType === "handover" ? "active" : "completed";
      await supabase
        .from(table)
        .update({ status: nextStatus })
        .eq("id", bookingId);

      return new Response(
        JSON.stringify({
          success: true,
          bookingId,
          otpType,
          newStatus: nextStatus,
          message: otpType === "handover" 
            ? "Handover confirmed! Rental is now active." 
            : "Return confirmed! Rental transaction completed successfully."
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 3. STATUS / CHECK
    const { data: statusRecords } = await supabase
      .from("booking_otps")
      .select("id, status, expires_at, created_at, attempts, max_attempts")
      .eq("booking_id", bookingId)
      .eq("otp_type", otpType)
      .order("created_at", { ascending: false })
      .limit(1);

    const latest = statusRecords && statusRecords[0];

    return new Response(
      JSON.stringify({
        hasActiveOtp: Boolean(latest && latest.status === "active" && new Date(latest.expires_at).getTime() > Date.now()),
        expiresAt: latest?.expires_at || null,
        attemptsRemaining: latest ? Math.max(0, latest.max_attempts - latest.attempts) : 5,
        status: latest?.status || "none"
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ error: err.message || "Internal server error." }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
